// AUTO-GENERATED by scripts/write-media.mjs — do not edit by hand.
// Reference photos sourced from Wikimedia Commons (license-clean, attributed).
import type { SpotMedia } from '../../spots/types'

export const SPOT_MEDIA: Record<string, SpotMedia[]> =
{
  "bayshore-boulevard": [
    {
      "src": "./spot-photos/skyline-of-tampa-florida-from-bayshore-blvd-9b4295.webp",
      "thumb": "./spot-photos/skyline-of-tampa-florida-from-bayshore-blvd-9b4295-thumb.webp",
      "caption": "Downtown skyline beyond the curving balustrade",
      "credit": "Original uploader was user:Tampa Gator at en.wikipedia",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASkyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg",
      "light": "daytime",
      "camera": "Nikon E885",
      "focalLengthMm": 8,
      "fNumber": 7.6,
      "shutter": "1/289",
      "iso": 100
    },
    {
      "src": "./spot-photos/tampa-bayshore-blvd-looking-north01-825e5b.webp",
      "thumb": "./spot-photos/tampa-bayshore-blvd-looking-north01-825e5b-thumb.webp",
      "caption": "WPA balustrade leading down the bayfront path",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Bayshore_Blvd_looking_north01.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak C875",
      "focalLengthMm": 7.8,
      "fNumber": 4,
      "shutter": "1/640",
      "iso": 64
    }
  ],
  "ballast-point-park": [
    {
      "src": "./spot-photos/view-of-downtown-tampa-from-the-pier-at-ballast-poin-b61f8a.webp",
      "thumb": "./spot-photos/view-of-downtown-tampa-from-the-pier-at-ballast-poin-b61f8a-thumb.webp",
      "caption": "Downtown skyline across the bay",
      "credit": "Heditor6",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AView_of_Downtown_Tampa_from_the_Pier_at_Ballast_Point_Park.JPG",
      "light": "daytime",
      "camera": "Canon PowerShot S3 IS",
      "focalLengthMm": 19,
      "fNumber": 8,
      "shutter": "1/250"
    },
    {
      "src": "./spot-photos/fishing-pier-at-ballast-point-park-efc031.webp",
      "thumb": "./spot-photos/fishing-pier-at-ballast-point-park-efc031-thumb.webp",
      "caption": "Fishing pier leading into stormy bay",
      "credit": "Heditor6",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AFishing_Pier_at_Ballast_Point_Park.JPG",
      "light": "daytime",
      "camera": "Canon PowerShot S3 IS",
      "focalLengthMm": 7.6,
      "fNumber": 4.5,
      "shutter": "1/2000"
    }
  ],
  "davis-islands-beach": [
    {
      "src": "./spot-photos/davis-islands-tampa-florida-usa-panoramio-ed339d.webp",
      "thumb": "./spot-photos/davis-islands-tampa-florida-usa-panoramio-ed339d-thumb.webp",
      "caption": "Moored sailboats with skyline backdrop over basin",
      "credit": "Roman Eugeniusz",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADavis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio.jpg",
      "light": "evening-golden",
      "camera": "Nikon D5100",
      "focalLengthMm": 125,
      "fNumber": 8,
      "shutter": "1/250",
      "iso": 110
    },
    {
      "src": "./spot-photos/davis-islands-tampa-florida-usa-panoramio-1-da3e18.webp",
      "thumb": "./spot-photos/davis-islands-tampa-florida-usa-panoramio-1-da3e18-thumb.webp",
      "caption": "Yacht basin and downtown skyline beyond",
      "credit": "Roman Eugeniusz",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADavis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio_(1).jpg",
      "light": "daytime",
      "camera": "Nikon D5100",
      "focalLengthMm": 48,
      "fNumber": 8,
      "shutter": "1/250",
      "iso": 180
    },
    {
      "src": "./spot-photos/summer-storm-rolling-behind-downtown-tampa-from-davi-81326f.webp",
      "thumb": "./spot-photos/summer-storm-rolling-behind-downtown-tampa-from-davi-81326f-thumb.webp",
      "caption": "Tampa skyline across the bay, stormy sky",
      "credit": "Robert Neff",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASummer_Storm_rolling_behind_downtown_Tampa_from_Davis_Island.jpg",
      "light": "daytime",
      "camera": "Nikon D7000",
      "focalLengthMm": 24,
      "fNumber": 5,
      "shutter": "1/100",
      "iso": 400
    }
  ],
  "curtis-hixon-waterfront-park": [
    {
      "src": "./spot-photos/curtis-hixon-park-tampa-florida-united-states-panora-0b24cd.webp",
      "thumb": "./spot-photos/curtis-hixon-park-tampa-florida-united-states-panora-0b24cd-thumb.webp",
      "caption": "Fountains and skyline glowing at blue hour",
      "credit": "Michelle Maria",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACurtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_(2).jpg",
      "light": "blue-hour",
      "camera": "Samsung Galaxy Nexus",
      "focalLengthMm": 3.4,
      "fNumber": 2.8,
      "shutter": "1/8"
    },
    {
      "src": "./spot-photos/curtis-hixon-park-tampa-florida-united-states-panora-9448fc.webp",
      "thumb": "./spot-photos/curtis-hixon-park-tampa-florida-united-states-panora-9448fc-thumb.webp",
      "caption": "Downtown towers and palms at dusk",
      "credit": "Michelle Maria",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACurtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_(1).jpg",
      "light": "blue-hour",
      "camera": "Samsung Galaxy Nexus",
      "focalLengthMm": 3.4,
      "fNumber": 2.8,
      "shutter": "1/15"
    }
  ],
  "tampa-riverwalk": [
    {
      "src": "./spot-photos/tampa-riverwalk-01-46a58e.webp",
      "thumb": "./spot-photos/tampa-riverwalk-01-46a58e-thumb.webp",
      "caption": "Lit Riverwalk path leading to glowing skyline",
      "credit": "Miosotis Jade",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Riverwalk_01.jpg",
      "light": "blue-hour",
      "camera": "Canon PowerShot SX130 IS",
      "focalLengthMm": 8.7,
      "fNumber": 8,
      "shutter": "1.6",
      "iso": 200
    },
    {
      "src": "./spot-photos/tampa-riverwalk-03-b440cc.webp",
      "thumb": "./spot-photos/tampa-riverwalk-03-b440cc-thumb.webp",
      "caption": "Skyline mirrored in the river at dusk",
      "credit": "Miosotis Jade",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Riverwalk_03.jpg",
      "light": "blue-hour",
      "camera": "Canon PowerShot SX130 IS",
      "focalLengthMm": 5,
      "fNumber": 8,
      "shutter": "5",
      "iso": 200
    },
    {
      "src": "./spot-photos/tampa-riverwalk-02-0237e4.webp",
      "thumb": "./spot-photos/tampa-riverwalk-02-0237e4-thumb.webp",
      "caption": "Downtown towers reflected across the river",
      "credit": "Miosotis Jade",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Riverwalk_02.jpg",
      "light": "blue-hour",
      "camera": "Canon PowerShot SX130 IS",
      "focalLengthMm": 5,
      "fNumber": 8,
      "shutter": "3.2",
      "iso": 200
    }
  ],
  "plant-park-ut-minarets": [
    {
      "src": "./spot-photos/old-tampa-bay-hotel-spire04-c184de.webp",
      "thumb": "./spot-photos/old-tampa-bay-hotel-spire04-c184de-thumb.webp",
      "caption": "Silver minaret dome against vivid blue sky",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AOld_Tampa_Bay_Hotel_spire04.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak C875",
      "focalLengthMm": 24,
      "fNumber": 5,
      "shutter": "1/800",
      "iso": 64
    },
    {
      "src": "./spot-photos/tampa-bay-hotel-2-ed569a.webp",
      "thumb": "./spot-photos/tampa-bay-hotel-2-ed569a-thumb.webp",
      "caption": "Golden domes and palm at dusk",
      "credit": "Zeng8r at English Wikipedia",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Bay_Hotel_2.jpg",
      "light": "evening-golden",
      "camera": "Olympus X550,D545Z,C480Z",
      "focalLengthMm": 13,
      "fNumber": 4,
      "shutter": "1/200",
      "iso": 50
    },
    {
      "src": "./spot-photos/old-tampa-bay-hotel-spire02-b878e6.webp",
      "thumb": "./spot-photos/old-tampa-bay-hotel-spire02-b878e6-thumb.webp",
      "caption": "Three silver minarets above brick facade",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AOld_Tampa_Bay_Hotel_spire02.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak C875",
      "focalLengthMm": 15,
      "fNumber": 4.5,
      "shutter": "1/500",
      "iso": 64
    }
  ],
  "henry-b-plant-museum": [
    {
      "src": "./spot-photos/old-tampa-bay-hotel-7297f8.webp",
      "thumb": "./spot-photos/old-tampa-bay-hotel-7297f8-thumb.webp",
      "caption": "Moorish minarets over brick facade and gardens",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AOld_Tampa_Bay_Hotel.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak C875",
      "focalLengthMm": 7.8,
      "fNumber": 2.8,
      "shutter": "1/640",
      "iso": 64
    },
    {
      "src": "./spot-photos/henry-b-plant-museum-9653e4.webp",
      "thumb": "./spot-photos/henry-b-plant-museum-9653e4-thumb.webp",
      "caption": "Silver minaret towers framed by palms",
      "credit": "Tsya 42",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHenry_B_Plant_Museum.jpg",
      "light": "evening-golden",
      "camera": "Nikon Coolpix S9900",
      "focalLengthMm": 5.2,
      "fNumber": 3.7,
      "shutter": "1/500",
      "iso": 125
    },
    {
      "src": "./spot-photos/henry-plant-museum-fletcher-lounge-ballroom-rotunda-deff71.webp",
      "thumb": "./spot-photos/henry-plant-museum-fletcher-lounge-ballroom-rotunda-deff71-thumb.webp",
      "caption": "Ornate Gilded-Age rotunda dome ceiling",
      "credit": "PeaceLoveHarmony",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHenry_Plant_Museum_Fletcher_Lounge_ballroom_rotunda.jpg",
      "light": "daytime",
      "camera": "samsung SM-G930VL",
      "focalLengthMm": 4.2,
      "fNumber": 1.7,
      "shutter": "1/60",
      "iso": 160
    }
  ],
  "sacred-heart-catholic-church": [
    {
      "src": "./spot-photos/tampa-sacred-heart-church04-dcc559.webp",
      "thumb": "./spot-photos/tampa-sacred-heart-church04-dcc559-thumb.webp",
      "caption": "Marble facade and rose window against clouds",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Sacred_Heart_Church04.jpg",
      "light": "daytime"
    },
    {
      "src": "./spot-photos/interior-sacred-heart-catholic-church-tampa-florida-674535.webp",
      "thumb": "./spot-photos/interior-sacred-heart-catholic-church-tampa-florida-674535-thumb.webp",
      "caption": "Ornate nave and marble columns to altar",
      "credit": "Boston Public Library",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AInterior_Sacred_Heart_Catholic_Church%2C_Tampa%2C_Florida.jpg",
      "camera": "Epson Exp10000XL10000"
    },
    {
      "src": "./spot-photos/tampa-sacred-heart-church06-a95a10.webp",
      "thumb": "./spot-photos/tampa-sacred-heart-church06-a95a10-thumb.webp",
      "caption": "Front-quarter view with dome on Florida Ave",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Sacred_Heart_Church06.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak Easyshare C195",
      "focalLengthMm": 5.9,
      "fNumber": 8,
      "shutter": "1/160",
      "iso": 64
    }
  ],
  "tampa-theatre": [
    {
      "src": "./spot-photos/tampa-theatre-2013-19a729.webp",
      "thumb": "./spot-photos/tampa-theatre-2013-19a729-thumb.webp",
      "caption": "Neon marquee and blade sign glowing at night",
      "credit": "MarieG33",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Theatre_2013.jpg",
      "light": "night-astro",
      "camera": "Nikon D60",
      "focalLengthMm": 18,
      "fNumber": 3.5,
      "shutter": "1/15",
      "iso": 400
    },
    {
      "src": "./spot-photos/tampatheatre-front05-cbee94.webp",
      "thumb": "./spot-photos/tampatheatre-front05-cbee94-thumb.webp",
      "caption": "Iconic vertical TAMPA blade sign from below",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampaTheatre_front05.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak C875",
      "focalLengthMm": 7.8,
      "fNumber": 2.8,
      "shutter": "1/100",
      "iso": 64
    },
    {
      "src": "./spot-photos/tampatheatre01-8be31e.webp",
      "thumb": "./spot-photos/tampatheatre01-8be31e-thumb.webp",
      "caption": "Marquee and office building with palms",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampaTheatre01.jpg",
      "light": "daytime"
    }
  ],
  "ybor-city": [
    {
      "src": "./spot-photos/white-tower-in-ybor-city-tampa-florida-d0ea47.webp",
      "thumb": "./spot-photos/white-tower-in-ybor-city-tampa-florida-d0ea47-thumb.webp",
      "caption": "Historic corner building with green-tiled tower",
      "credit": "psyberartist",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWhite_tower_in_Ybor_City%2C_Tampa_Florida.jpg",
      "light": "daytime",
      "camera": "Canon Eos 6D",
      "focalLengthMm": 62,
      "fNumber": 22,
      "shutter": "1/160",
      "iso": 400
    },
    {
      "src": "./spot-photos/centro-ybor-ybor-city-tampa-florida-b9ef8f.webp",
      "thumb": "./spot-photos/centro-ybor-ybor-city-tampa-florida-b9ef8f-thumb.webp",
      "caption": "Centro Ybor facade with vintage streetcar",
      "credit": "Peter K Burian",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACentro_Ybor%2C_Ybor_City%2C_Tampa%2C_Florida.jpg",
      "light": "daytime",
      "camera": "Nikon D800",
      "focalLengthMm": 38,
      "fNumber": 4,
      "shutter": "1/1250",
      "iso": 500
    },
    {
      "src": "./spot-photos/ybor-city-museum-state-park-tampa-florida-284a3b.webp",
      "thumb": "./spot-photos/ybor-city-museum-state-park-tampa-florida-284a3b-thumb.webp",
      "caption": "Yellow-brick Ybor City Museum with flags",
      "credit": "Peter K Burian",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AYbor_City_Museum_State_Park%2C_Tampa%2C_Florida.jpg",
      "light": "daytime",
      "camera": "Nikon D800",
      "focalLengthMm": 40,
      "fNumber": 6.3,
      "shutter": "1/400",
      "iso": 400
    }
  ],
  "lettuce-lake-park": [
    {
      "src": "./spot-photos/great-blue-heron-49111167428-f3e29a.webp",
      "thumb": "./spot-photos/great-blue-heron-49111167428-f3e29a-thumb.webp",
      "caption": "Great blue heron perched over still water",
      "credit": "Trish Hartmann from Tampa, Florida, USA",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AGreat_Blue_Heron_(49111167428).jpg",
      "light": "morning-golden",
      "camera": "Nikon D850",
      "focalLengthMm": 300,
      "fNumber": 5.6,
      "shutter": "1/750",
      "iso": 160
    },
    {
      "src": "./spot-photos/kayaking-on-the-hillsborough-river-681a51.webp",
      "thumb": "./spot-photos/kayaking-on-the-hillsborough-river-681a51-thumb.webp",
      "caption": "Cypress and palm mirrored in calm river",
      "credit": "Mwanner",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AKayaking_on_the_Hillsborough_River.jpg",
      "light": "daytime"
    },
    {
      "src": "./spot-photos/barred-owl-at-lettuce-lake-12735495095-9245f4.webp",
      "thumb": "./spot-photos/barred-owl-at-lettuce-lake-12735495095-9245f4-thumb.webp",
      "caption": "Barred owl on a mossy branch",
      "credit": "Trish Hartmann from Tampa, Florida, USA",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABarred_Owl_at_Lettuce_Lake_(12735495095).jpg",
      "light": "open-shade",
      "camera": "Nikon D5100",
      "focalLengthMm": 200,
      "fNumber": 5.6,
      "shutter": "1/320",
      "iso": 400
    }
  ],
  "usf-botanical-gardens": [
    {
      "src": "./spot-photos/dyckia-red2-usf-asit-efb17c.webp",
      "thumb": "./spot-photos/dyckia-red2-usf-asit-efb17c-thumb.webp",
      "caption": "Vivid red bromeliad rosette, exotic collection",
      "credit": "Asit K. Ghosh Thaumaturgist",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADyckia_Red2_USF_Asit.jpg",
      "light": "daytime",
      "camera": "Sony DSC-H9",
      "focalLengthMm": 6.8,
      "fNumber": 4,
      "shutter": "1/200",
      "iso": 100
    },
    {
      "src": "./spot-photos/balsampear02-usf-asit-d4ccbe.webp",
      "thumb": "./spot-photos/balsampear02-usf-asit-d4ccbe-thumb.webp",
      "caption": "Backlit orange fruit glowing in foliage",
      "credit": "asitkghosh@yahoo.com Thaumaturgist",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABalsamPear02_USF_Asit.JPG",
      "light": "daytime",
      "camera": "Sony DSC-H9",
      "focalLengthMm": 19,
      "fNumber": 4.5,
      "shutter": "1/500",
      "iso": 100
    },
    {
      "src": "./spot-photos/balsampear04-usf-asit-c22356.webp",
      "thumb": "./spot-photos/balsampear04-usf-asit-c22356-thumb.webp",
      "caption": "Bright orange bloom among lush greenery",
      "credit": "asitkghosh@yahoo.com Thaumaturgist",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABalsamPear04_USF_Asit.JPG",
      "light": "daytime",
      "camera": "Sony DSC-H9",
      "focalLengthMm": 14,
      "fNumber": 4.5,
      "shutter": "1/400",
      "iso": 100
    }
  ],
  "sunken-gardens": [
    {
      "src": "./spot-photos/coy-pond-at-the-entrance-to-the-sunken-gardens-st-pe-845d92.webp",
      "thumb": "./spot-photos/coy-pond-at-the-entrance-to-the-sunken-gardens-st-pe-845d92-thumb.webp",
      "caption": "Grotto waterfall over koi-and-lily pond",
      "credit": "Florida Memory",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACoy_pond_at_the_entrance_to_the_Sunken_Gardens-_St._Petersburg%2C_Florida_(8527270077).jpg",
      "light": "daytime"
    },
    {
      "src": "./spot-photos/scarlet-ibis-at-sunken-gardens-st-petersburg-florida-f524c5.webp",
      "thumb": "./spot-photos/scarlet-ibis-at-sunken-gardens-st-petersburg-florida-f524c5-thumb.webp",
      "caption": "Scarlet ibis portrait in soft shade",
      "credit": "Florida Memory",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AScarlet_Ibis_at_Sunken_Gardens-_St._Petersburg%2C_Florida_(8528405744).jpg",
      "light": "open-shade"
    },
    {
      "src": "./spot-photos/st-petersburg-fl-sunken-gardens-gate01-bf22df.webp",
      "thumb": "./spot-photos/st-petersburg-fl-sunken-gardens-gate01-bf22df-thumb.webp",
      "caption": "Gate framed by bougainvillea and palms",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Petersburg_FL_Sunken_Gardens_gate01.jpg",
      "light": "open-shade",
      "camera": "Eastman Kodak Easyshare C195",
      "focalLengthMm": 5.9,
      "fNumber": 3.3,
      "shutter": "1/60",
      "iso": 64
    }
  ],
  "fort-de-soto-park": [
    {
      "src": "./spot-photos/sunset-on-north-beach-at-fort-de-soto-park-8a829b.webp",
      "thumb": "./spot-photos/sunset-on-north-beach-at-fort-de-soto-park-8a829b-thumb.webp",
      "caption": "Gulf sunset over calm North Beach surf",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASunset_on_North_Beach_at_Fort_De_Soto_Park.jpg",
      "light": "sunset",
      "camera": "Sony Cybershot",
      "focalLengthMm": 7,
      "fNumber": 4.8,
      "shutter": "1/470",
      "iso": 100
    },
    {
      "src": "./spot-photos/fort-de-soto-park-st-petersburg-florida-gulfcoast-15-89e994.webp",
      "thumb": "./spot-photos/fort-de-soto-park-st-petersburg-florida-gulfcoast-15-89e994-thumb.webp",
      "caption": "White-sand spit and lagoon with passing yacht",
      "credit": "Reinhard Link from Germany",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AFort_de_Soto_Park_%40_St.Petersburg_(Florida_-_Gulfcoast)_(15684290600).jpg",
      "light": "daytime",
      "camera": "Casio EX-H15",
      "focalLengthMm": 22,
      "fNumber": 5.2,
      "shutter": "1/800",
      "iso": 64
    }
  ],
  "honeymoon-island-sp": [
    {
      "src": "./spot-photos/honeymoon-island-state-park-image-1-ff1a72.webp",
      "thumb": "./spot-photos/honeymoon-island-state-park-image-1-ff1a72-thumb.webp",
      "caption": "Turquoise Gulf surf on shell beach",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoneymoon_Island_State_Park_(Image_1).jpg",
      "light": "daytime",
      "camera": "Sony Cybershot",
      "focalLengthMm": 7,
      "fNumber": 8,
      "shutter": "1/985",
      "iso": 100
    },
    {
      "src": "./spot-photos/honeymoon-island-state-park-image-3-6f3182.webp",
      "thumb": "./spot-photos/honeymoon-island-state-park-image-3-6f3182-thumb.webp",
      "caption": "Wooden swing facing the Gulf",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoneymoon_Island_State_Park_(Image_3).jpg",
      "light": "daytime",
      "camera": "Sony Cybershot",
      "focalLengthMm": 7,
      "fNumber": 8,
      "shutter": "1/985",
      "iso": 100
    },
    {
      "src": "./spot-photos/honeymoon-island-state-park-image-2-b31bf8.webp",
      "thumb": "./spot-photos/honeymoon-island-state-park-image-2-b31bf8-thumb.webp",
      "caption": "Leaning tree over shell shoreline",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoneymoon_Island_State_Park_(Image_2).jpg",
      "light": "daytime",
      "camera": "Sony Cybershot",
      "focalLengthMm": 7,
      "fNumber": 8,
      "shutter": "1/985",
      "iso": 100
    }
  ],
  "sunshine-skyway-fishing-piers": [
    {
      "src": "./spot-photos/sunshine-skyway-bridge-08d716.webp",
      "thumb": "./spot-photos/sunshine-skyway-bridge-08d716-thumb.webp",
      "caption": "Lit Skyway span over the bay at dusk",
      "credit": "The original uploader was Caltrop at English Wikipedia .",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASunshine_Skyway_Bridge.jpg",
      "light": "blue-hour"
    },
    {
      "src": "./spot-photos/2010-09-10-sunshine-skyway-bridge-896b1c.webp",
      "thumb": "./spot-photos/2010-09-10-sunshine-skyway-bridge-896b1c-thumb.webp",
      "caption": "Yellow cables fanning to the tower",
      "credit": "Joe King",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A2010-09-10_Sunshine_Skyway_Bridge.jpg",
      "light": "daytime",
      "camera": "Olympus u720SW,S720SW",
      "focalLengthMm": 6.7,
      "fNumber": 5,
      "shutter": "1/320",
      "iso": 64
    },
    {
      "src": "./spot-photos/sunshine-skyway-bridge-1sc-2563-abd8ba.webp",
      "thumb": "./spot-photos/sunshine-skyway-bridge-1sc-2563-abd8ba-thumb.webp",
      "caption": "Bridge silhouette with cargo ship at golden hour",
      "credit": "Robert Neff",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASunshine_Skyway_Bridge_1SC_2563.jpg",
      "light": "evening-golden",
      "camera": "Nikon D7000",
      "focalLengthMm": 60,
      "fNumber": 16,
      "shutter": "1/160",
      "iso": 100
    }
  ],
  "st-pete-pier": [
    {
      "src": "./spot-photos/2021-st-pete-pier-1-019e46.webp",
      "thumb": "./spot-photos/2021-st-pete-pier-1-019e46-thumb.webp",
      "caption": "Modern pier head with palms, blue sky",
      "credit": "Beyond My Ken",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A2021_St._Pete_Pier_1.jpg",
      "light": "daytime",
      "camera": "Apple iPhone 8",
      "focalLengthMm": 4,
      "fNumber": 1.8,
      "shutter": "1/2558"
    },
    {
      "src": "./spot-photos/st-pete-pier-west-d78484.webp",
      "thumb": "./spot-photos/st-pete-pier-west-d78484-thumb.webp",
      "caption": "Bending Arc net sculpture overhead",
      "credit": "Jackdude101",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Pier_-_West.jpg",
      "light": "daytime",
      "camera": "Sony DSC-W830",
      "focalLengthMm": 4.5,
      "fNumber": 8,
      "shutter": "1/200",
      "iso": 80
    },
    {
      "src": "./spot-photos/st-pete-pier-head-structure-19f52c.webp",
      "thumb": "./spot-photos/st-pete-pier-head-structure-19f52c-thumb.webp",
      "caption": "Pier head structure over the bay",
      "credit": "Adog",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Pier_head_structure.jpg",
      "light": "daytime",
      "camera": "Apple iPhone 11",
      "focalLengthMm": 4.3,
      "fNumber": 1.8,
      "shutter": "1/2315",
      "iso": 32
    }
  ],
  "vinoy-park": [
    {
      "src": "./spot-photos/st-pete-vinoy-pano01-ffa6f0.webp",
      "thumb": "./spot-photos/st-pete-vinoy-pano01-ffa6f0-thumb.webp",
      "caption": "Pink Vinoy hotel framed by palms",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Vinoy_pano01.jpg",
      "light": "daytime"
    },
    {
      "src": "./spot-photos/the-vinoy-hotel-04-ff911f.webp",
      "thumb": "./spot-photos/the-vinoy-hotel-04-ff911f-thumb.webp",
      "caption": "Ornate VINOY window with palm",
      "credit": "MiaCass16",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AThe_Vinoy_Hotel_04.jpg",
      "light": "daytime",
      "camera": "Sony DSC-H300",
      "focalLengthMm": 4.5,
      "fNumber": 3,
      "shutter": "1/1000",
      "iso": 80
    },
    {
      "src": "./spot-photos/st-pete-vinoy-detail02-0d123b.webp",
      "thumb": "./spot-photos/st-pete-vinoy-detail02-0d123b-thumb.webp",
      "caption": "Pink facade detail against blue sky",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Vinoy_detail02.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak C875",
      "focalLengthMm": 24,
      "fNumber": 5,
      "shutter": "1/500",
      "iso": 64
    }
  ],
  "dali-museum": [
    {
      "src": "./spot-photos/salvador-dali-museum-panoramio-17-69ab09.webp",
      "thumb": "./spot-photos/salvador-dali-museum-panoramio-17-69ab09-thumb.webp",
      "caption": "Enigma glass bubble framed by cypress, dramatic sky",
      "credit": "Art Anderson",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASalvador_Dali_Museum_-_panoramio_(17).jpg",
      "light": "evening-golden",
      "camera": "Canon PowerShot S120",
      "focalLengthMm": 6,
      "fNumber": 3.5,
      "shutter": "1/2000",
      "iso": 160
    },
    {
      "src": "./spot-photos/salvador-dali-museum-a151ac.webp",
      "thumb": "./spot-photos/salvador-dali-museum-a151ac-thumb.webp",
      "caption": "Full Enigma bubble and concrete museum, palms",
      "credit": "Taty2007",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASalvador_Dal%C3%AD_Museum.JPG",
      "light": "daytime",
      "camera": "Canon Eos 50D",
      "focalLengthMm": 28,
      "fNumber": 7.1,
      "shutter": "1/160",
      "iso": 100
    },
    {
      "src": "./spot-photos/atrium-of-salvador-dali-museum-in-florida-605a73.webp",
      "thumb": "./spot-photos/atrium-of-salvador-dali-museum-in-florida-605a73-thumb.webp",
      "caption": "Helical staircase under the geodesic glass dome",
      "credit": "LovelyLillith",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AAtrium_of_Salvador_Dal%C3%AD_Museum_in_Florida.jpg",
      "light": "daytime",
      "camera": "Nokia Lumia 925",
      "fNumber": 2,
      "shutter": "1/1299",
      "iso": 100
    }
  ],
  "weedon-island-preserve": [
    {
      "src": "./spot-photos/weedon-island-preserve-panoramio-a814c7.webp",
      "thumb": "./spot-photos/weedon-island-preserve-panoramio-a814c7-thumb.webp",
      "caption": "Mangrove boardwalk leading into the preserve",
      "credit": "jesseasmith",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWeedon_Island_preserve_-_panoramio.jpg",
      "light": "daytime",
      "camera": "Nikon D5000",
      "focalLengthMm": 10,
      "fNumber": 10,
      "shutter": "1/250",
      "iso": 200
    },
    {
      "src": "./spot-photos/weedon-island-preserve-panoramio-2-49cdf9.webp",
      "thumb": "./spot-photos/weedon-island-preserve-panoramio-2-49cdf9-thumb.webp",
      "caption": "Boardwalk vanishing under towering cumulus clouds",
      "credit": "jesseasmith",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWeedon_Island_preserve_-_panoramio_(2).jpg",
      "light": "daytime",
      "camera": "Nikon D5000",
      "focalLengthMm": 10,
      "fNumber": 11,
      "shutter": "1/640",
      "iso": 200
    },
    {
      "src": "./spot-photos/weeden-island01-9a4961.webp",
      "thumb": "./spot-photos/weeden-island01-9a4961-thumb.webp",
      "caption": "Mangrove wetlands and bay from tower",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWeeden_Island01.jpg",
      "light": "daytime"
    }
  ],
  "cathedral-st-peter-episcopal": [
    {
      "src": "./spot-photos/st-petersburg-fl-downtown-st-petersburg-historic-dis-1446c3.webp",
      "thumb": "./spot-photos/st-petersburg-fl-downtown-st-petersburg-historic-dis-1446c3-thumb.webp",
      "caption": "Brick gable, stained glass and spire",
      "credit": "Jrozwado",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt_Petersburg%2C_FL_-_Downtown_St_Petersburg_Historic_District_-_Cathedral_Church_of_St_Peter_(Episcopal)_(3).jpg",
      "light": "evening-golden",
      "camera": "Nikon D7100",
      "focalLengthMm": 24,
      "fNumber": 16,
      "shutter": "1/1000",
      "iso": 1250
    },
    {
      "src": "./spot-photos/st-pete-episc-cathedral03-5bb34c.webp",
      "thumb": "./spot-photos/st-pete-episc-cathedral03-5bb34c-thumb.webp",
      "caption": "Blonde-brick spire against blue sky",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Episc_Cathedral03.jpg",
      "light": "daytime",
      "camera": "Eastman Kodak C875",
      "focalLengthMm": 7.8,
      "fNumber": 4,
      "shutter": "1/800",
      "iso": 64
    },
    {
      "src": "./spot-photos/cathedral-church-of-st-peter-at-140-4th-st-n-in-st-p-5e7714.webp",
      "thumb": "./spot-photos/cathedral-church-of-st-peter-at-140-4th-st-n-in-st-p-5e7714-thumb.webp",
      "caption": "Full three-quarter view of cathedral",
      "credit": "Joseph Janney Steinmetz",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_Church_of_St._Peter_at_140_4th_St._N._in_St._Petersburg%2C_Florida.jpg",
      "light": "daytime"
    }
  ],
  "cathedral-st-jude-apostle": [
    {
      "src": "./spot-photos/cathedral-of-saint-jude-the-apostle-st-petersburg-fl-76a65d.webp",
      "thumb": "./spot-photos/cathedral-of-saint-jude-the-apostle-st-petersburg-fl-76a65d-thumb.webp",
      "caption": "Altar and crucifix with modern stained glass",
      "credit": "Nheyob",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_of_Saint_Jude_the_Apostle_(St._Petersburg%2C_Florida)_-_sanctuary_2.jpg",
      "light": "daytime",
      "camera": "Canon PowerShot G9 X",
      "focalLengthMm": 11,
      "fNumber": 2.8,
      "shutter": "1/30",
      "iso": 125
    },
    {
      "src": "./spot-photos/cathedral-of-saint-jude-the-apostle-st-petersburg-fl-fe9dd8.webp",
      "thumb": "./spot-photos/cathedral-of-saint-jude-the-apostle-st-petersburg-fl-fe9dd8-thumb.webp",
      "caption": "Nave pews toward the altar",
      "credit": "Nheyob",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_of_Saint_Jude_the_Apostle_(St._Petersburg%2C_Florida)_-_nave.jpg",
      "light": "daytime",
      "camera": "Canon PowerShot G9 X",
      "focalLengthMm": 10,
      "fNumber": 2.2,
      "shutter": "1/60",
      "iso": 125
    },
    {
      "src": "./spot-photos/cathedral-of-saint-jude-the-apostle-st-petersburg-fl-0f91bc.webp",
      "thumb": "./spot-photos/cathedral-of-saint-jude-the-apostle-st-petersburg-fl-0f91bc-thumb.webp",
      "caption": "Orange spire and cathedral name sign",
      "credit": "Nheyob",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_of_Saint_Jude_the_Apostle_(St._Petersburg%2C_Florida)_-_exterior.jpg",
      "light": "daytime",
      "camera": "Canon PowerShot G9 X",
      "focalLengthMm": 10,
      "fNumber": 4,
      "shutter": "1/100",
      "iso": 160
    }
  ],
  "stpete-shine-murals": [
    {
      "src": "./spot-photos/before-i-die-mural-22bbae.webp",
      "thumb": "./spot-photos/before-i-die-mural-22bbae-thumb.webp",
      "caption": "\"Before I die\" wall with bikes, people",
      "credit": "Xrzt",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABefore_I_Die_Mural.jpg",
      "light": "daytime",
      "camera": "Nikon D7000",
      "focalLengthMm": 50,
      "fNumber": 6.3,
      "shutter": "1/2000",
      "iso": 200
    }
  ],
  "fred-howard-park": [
    {
      "src": "./spot-photos/howard-park-tarpon-469b88.webp",
      "thumb": "./spot-photos/howard-park-tarpon-469b88-thumb.webp",
      "caption": "Gulf sunset behind beach palm silhouettes",
      "credit": "VitaleBaby at English Wikipedia",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoward_Park_Tarpon.jpg",
      "light": "sunset",
      "camera": "Canon PowerShot Elph 350 HS",
      "focalLengthMm": 20,
      "fNumber": 5,
      "shutter": "1/500",
      "iso": 250
    },
    {
      "src": "./spot-photos/porsche-and-parasail-ba34a0.webp",
      "thumb": "./spot-photos/porsche-and-parasail-ba34a0-thumb.webp",
      "caption": "Kite-surfer rig over windy causeway",
      "credit": "Xrzt",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3APorsche_and_parasail.jpg",
      "light": "daytime",
      "camera": "Nikon D7000",
      "focalLengthMm": 180,
      "fNumber": 9,
      "shutter": "1/1250",
      "iso": 200
    }
  ],
  "azure-tampa-edition": [
    {
      "src": "./spot-photos/editiontampa-d6d727.webp",
      "thumb": "./spot-photos/editiontampa-d6d727-thumb.webp",
      "caption": "The Tampa EDITION — home of the Azure rooftop",
      "credit": "Chiefmiz",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:EditionTampa.jpg",
      "light": "daytime"
    }
  ],
  "beacon-jw-marriott": [
    {
      "src": "./spot-photos/downtown-tampa-florida-9d7ff2.webp",
      "thumb": "./spot-photos/downtown-tampa-florida-9d7ff2-thumb.webp",
      "caption": "Downtown Tampa skyline — the kind of view from the rooftop",
      "credit": "Clément Bardot",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Downtown_Tampa,_Florida.jpg",
      "light": "daytime",
      "camera": "Nikon D5100",
      "focalLengthMm": 22,
      "fNumber": 7.1,
      "shutter": "1/1600",
      "iso": 400
    }
  ],
  "mbird-armature-works": [
    {
      "src": "./spot-photos/tampa-skyline-eric-statzer-707126.webp",
      "thumb": "./spot-photos/tampa-skyline-eric-statzer-707126-thumb.webp",
      "caption": "Downtown skyline across the water from the Heights",
      "credit": "Eric Statzer",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tampa_Skyline_-_Eric_Statzer.jpg",
      "light": "daytime",
      "camera": "Apple iPhone X",
      "focalLengthMm": 4,
      "fNumber": 1.8,
      "shutter": "1/1919"
    }
  ],
  "edge-epicurean": [
    {
      "src": "./spot-photos/downtown-tampa-58977580-e5dd16.webp",
      "thumb": "./spot-photos/downtown-tampa-58977580-e5dd16-thumb.webp",
      "caption": "The distant downtown skyline at golden hour",
      "credit": "Steven Buehler",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Downtown_Tampa_(58977580).jpeg",
      "light": "evening-golden",
      "camera": "Nikon Coolpix L820",
      "focalLengthMm": 76,
      "fNumber": 5.7,
      "shutter": "1/125",
      "iso": 125
    }
  ],
  "tampa-murals": [
    {
      "src": "./spot-photos/14492170902-aeffc419dd-b-6f7d0c.webp",
      "thumb": "./spot-photos/14492170902-aeffc419dd-z-82fe35-thumb.webp",
      "caption": "The 'Tampa Postcard' mural (by Carl Cowden III) at golden hour",
      "credit": "Photomatt28 (Flickr)",
      "license": "CC BY-NC-ND 2.0",
      "sourceUrl": "https://www.flickr.com/photos/46837385@N03/14492170902",
      "light": "evening-golden"
    }
  ]
}
