// Turn the workflow's picks (by index) + candidates.json into a per-city media
// file (src/data/spot-media/<region>.ts — cities must never share one; see
// docs/SCALING.md finding 4). Picks reference candidate indices only, so URLs
// come from our verified candidates (no fabrication).
// Run: node scripts/write-media.mjs [region]   (default: tampa-bay)
import { readFileSync, writeFileSync } from 'node:fs'

const REGION = process.argv[2] ?? 'tampa-bay'

const LIGHTS = new Set([
  'sunrise', 'morning-golden', 'blue-hour', 'daytime',
  'evening-golden', 'sunset', 'night-astro', 'open-shade',
])

const cands = JSON.parse(readFileSync('scripts/candidates.json', 'utf8'))
const picks = JSON.parse(readFileSync('scripts/picks.json', 'utf8'))

const out = {}
let total = 0
for (const r of picks) {
  const list = cands[r.spotId]
  if (!list || !Array.isArray(r.picks)) continue
  // hero first, then the rest, dedupe by src
  const ordered = [...r.picks].sort((a, b) => (b.hero ? 1 : 0) - (a.hero ? 1 : 0))
  const media = []
  const seen = new Set()
  for (const p of ordered) {
    const c = list[p.i]
    if (!c || !c.src || seen.has(c.src)) continue
    seen.add(c.src)
    const m = {
      src: c.src,
      thumb: c.thumb,
      caption: (p.caption || '').trim(),
      credit: c.artist || 'Wikimedia Commons',
      license: c.license,
      sourceUrl: c.sourceUrl,
    }
    if (p.light && LIGHTS.has(p.light)) m.light = p.light
    if (m.caption) media.push(m)
  }
  if (media.length) { out[r.spotId] = media; total += media.length }
}

const header = `// AUTO-GENERATED by scripts/write-media.mjs — do not edit by hand.
// Reference photos sourced from Wikimedia Commons (license-clean, attributed).
import type { SpotMedia } from '../../spots/types'

export const SPOT_MEDIA: Record<string, SpotMedia[]> =\n`
writeFileSync(`src/data/spot-media/${REGION}.ts`, header + JSON.stringify(out, null, 2) + '\n')
console.log(`wrote src/data/spot-media/${REGION}.ts: ${Object.keys(out).length} spots, ${total} photos`)
console.log('spots:', Object.keys(out).join(', '))
