// AUTO-GENERATED by scripts/write-media.mjs — do not edit by hand.
// Reference photos sourced from Wikimedia Commons (license-clean, attributed).
import type { SpotMedia } from '../spots/types'

export const SPOT_MEDIA: Record<string, SpotMedia[]> =
{
  "bayshore-boulevard": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Skyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg/1280px-Skyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Skyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg/500px-Skyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg",
      "caption": "Downtown skyline beyond the curving balustrade",
      "credit": "Original uploader was user:Tampa Gator at en.wikipedia",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASkyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg",
      "light": "daytime",
      "camera": "E885",
      "focalLengthMm": 8,
      "fNumber": 7.6,
      "shutter": "1/289",
      "iso": 100
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Tampa_Bayshore_Blvd_looking_north01.jpg/1280px-Tampa_Bayshore_Blvd_looking_north01.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Tampa_Bayshore_Blvd_looking_north01.jpg/500px-Tampa_Bayshore_Blvd_looking_north01.jpg",
      "caption": "WPA balustrade leading down the bayfront path",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Bayshore_Blvd_looking_north01.jpg",
      "light": "daytime",
      "camera": "KODAK C875 ZOOM DIGITAL CAMERA",
      "focalLengthMm": 7.8,
      "fNumber": 4,
      "shutter": "1/640",
      "iso": 64
    }
  ],
  "ballast-point-park": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/View_of_Downtown_Tampa_from_the_Pier_at_Ballast_Point_Park.JPG/1280px-View_of_Downtown_Tampa_from_the_Pier_at_Ballast_Point_Park.JPG",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/View_of_Downtown_Tampa_from_the_Pier_at_Ballast_Point_Park.JPG/500px-View_of_Downtown_Tampa_from_the_Pier_at_Ballast_Point_Park.JPG",
      "caption": "Downtown skyline across the bay",
      "credit": "Heditor6",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AView_of_Downtown_Tampa_from_the_Pier_at_Ballast_Point_Park.JPG",
      "light": "daytime",
      "camera": "Canon PowerShot S3 IS",
      "focalLengthMm": 19,
      "fNumber": 8,
      "shutter": "1/250"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Fishing_Pier_at_Ballast_Point_Park.JPG/1280px-Fishing_Pier_at_Ballast_Point_Park.JPG",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Fishing_Pier_at_Ballast_Point_Park.JPG/500px-Fishing_Pier_at_Ballast_Point_Park.JPG",
      "caption": "Fishing pier leading into stormy bay",
      "credit": "Heditor6",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AFishing_Pier_at_Ballast_Point_Park.JPG",
      "light": "daytime",
      "camera": "Canon PowerShot S3 IS",
      "focalLengthMm": 7.6,
      "fNumber": 4.5,
      "shutter": "1/2000"
    }
  ],
  "davis-islands-beach": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio.jpg/1280px-Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio.jpg/500px-Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio.jpg",
      "caption": "Moored sailboats with skyline backdrop over basin",
      "credit": "Roman Eugeniusz",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADavis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio.jpg",
      "light": "evening-golden",
      "camera": "NIKON D5100",
      "focalLengthMm": 125,
      "fNumber": 8,
      "shutter": "1/250",
      "iso": 110
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio_%281%29.jpg/1280px-Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio_%281%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio_%281%29.jpg/500px-Davis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio_%281%29.jpg",
      "caption": "Yacht basin and downtown skyline beyond",
      "credit": "Roman Eugeniusz",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADavis_Islands%2CTampa%2CFlorida%2CUSA._-_panoramio_(1).jpg",
      "light": "daytime",
      "camera": "NIKON D5100",
      "focalLengthMm": 48,
      "fNumber": 8,
      "shutter": "1/250",
      "iso": 180
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/0/04/Summer_Storm_rolling_behind_downtown_Tampa_from_Davis_Island.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Summer_Storm_rolling_behind_downtown_Tampa_from_Davis_Island.jpg/500px-Summer_Storm_rolling_behind_downtown_Tampa_from_Davis_Island.jpg",
      "caption": "Tampa skyline across the bay, stormy sky",
      "credit": "Robert Neff",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASummer_Storm_rolling_behind_downtown_Tampa_from_Davis_Island.jpg",
      "light": "daytime",
      "camera": "NIKON D7000",
      "focalLengthMm": 24,
      "fNumber": 5,
      "shutter": "1/100",
      "iso": 400
    }
  ],
  "curtis-hixon-waterfront-park": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%282%29.jpg/1280px-Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%282%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%282%29.jpg/500px-Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%282%29.jpg",
      "caption": "Fountains and skyline glowing at blue hour",
      "credit": "Michelle Maria",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACurtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_(2).jpg",
      "light": "blue-hour",
      "camera": "Galaxy Nexus",
      "focalLengthMm": 3.4,
      "fNumber": 2.8,
      "shutter": "1/8"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%281%29.jpg/1280px-Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%281%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%281%29.jpg/500px-Curtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_%281%29.jpg",
      "caption": "Downtown towers and palms at dusk",
      "credit": "Michelle Maria",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACurtis_Hixon_Park_Tampa_Florida_United_States_-_panoramio_(1).jpg",
      "light": "blue-hour",
      "camera": "Galaxy Nexus",
      "focalLengthMm": 3.4,
      "fNumber": 2.8,
      "shutter": "1/15"
    }
  ],
  "tampa-riverwalk": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Tampa_Riverwalk_01.jpg/1280px-Tampa_Riverwalk_01.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Tampa_Riverwalk_01.jpg/500px-Tampa_Riverwalk_01.jpg",
      "caption": "Lit Riverwalk path leading to glowing skyline",
      "credit": "Miosotis Jade",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Riverwalk_01.jpg",
      "light": "blue-hour",
      "camera": "Canon PowerShot SX130 IS",
      "focalLengthMm": 8.7,
      "fNumber": 8,
      "shutter": "1.6",
      "iso": 200
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Tampa_Riverwalk_03.jpg/1280px-Tampa_Riverwalk_03.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Tampa_Riverwalk_03.jpg/500px-Tampa_Riverwalk_03.jpg",
      "caption": "Skyline mirrored in the river at dusk",
      "credit": "Miosotis Jade",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Riverwalk_03.jpg",
      "light": "blue-hour",
      "camera": "Canon PowerShot SX130 IS",
      "focalLengthMm": 5,
      "fNumber": 8,
      "shutter": "5",
      "iso": 200
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Tampa_Riverwalk_02.jpg/1280px-Tampa_Riverwalk_02.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Tampa_Riverwalk_02.jpg/500px-Tampa_Riverwalk_02.jpg",
      "caption": "Downtown towers reflected across the river",
      "credit": "Miosotis Jade",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Riverwalk_02.jpg",
      "light": "blue-hour",
      "camera": "Canon PowerShot SX130 IS",
      "focalLengthMm": 5,
      "fNumber": 8,
      "shutter": "3.2",
      "iso": 200
    }
  ],
  "plant-park-ut-minarets": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Old_Tampa_Bay_Hotel_spire04.jpg/1280px-Old_Tampa_Bay_Hotel_spire04.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Old_Tampa_Bay_Hotel_spire04.jpg/500px-Old_Tampa_Bay_Hotel_spire04.jpg",
      "caption": "Silver minaret dome against vivid blue sky",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AOld_Tampa_Bay_Hotel_spire04.jpg",
      "light": "daytime",
      "camera": "KODAK C875 ZOOM DIGITAL CAMERA",
      "focalLengthMm": 24,
      "fNumber": 5,
      "shutter": "1/800",
      "iso": 64
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Tampa_Bay_Hotel_2.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Tampa_Bay_Hotel_2.jpg",
      "caption": "Golden domes and palm at dusk",
      "credit": "Zeng8r at English Wikipedia",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Bay_Hotel_2.jpg",
      "light": "evening-golden",
      "camera": "X550,D545Z,C480Z",
      "focalLengthMm": 13,
      "fNumber": 4,
      "shutter": "1/200",
      "iso": 50
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Old_Tampa_Bay_Hotel_spire02.jpg/1280px-Old_Tampa_Bay_Hotel_spire02.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Old_Tampa_Bay_Hotel_spire02.jpg/500px-Old_Tampa_Bay_Hotel_spire02.jpg",
      "caption": "Three silver minarets above brick facade",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AOld_Tampa_Bay_Hotel_spire02.jpg",
      "light": "daytime",
      "camera": "KODAK C875 ZOOM DIGITAL CAMERA",
      "focalLengthMm": 15,
      "fNumber": 4.5,
      "shutter": "1/500",
      "iso": 64
    }
  ],
  "henry-b-plant-museum": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Old_Tampa_Bay_Hotel.jpg/1280px-Old_Tampa_Bay_Hotel.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Old_Tampa_Bay_Hotel.jpg/500px-Old_Tampa_Bay_Hotel.jpg",
      "caption": "Moorish minarets over brick facade and gardens",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AOld_Tampa_Bay_Hotel.jpg",
      "light": "daytime",
      "camera": "KODAK C875 ZOOM DIGITAL CAMERA",
      "focalLengthMm": 7.8,
      "fNumber": 2.8,
      "shutter": "1/640",
      "iso": 64
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Henry_B_Plant_Museum.jpg/1280px-Henry_B_Plant_Museum.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Henry_B_Plant_Museum.jpg/500px-Henry_B_Plant_Museum.jpg",
      "caption": "Silver minaret towers framed by palms",
      "credit": "Tsya 42",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHenry_B_Plant_Museum.jpg",
      "light": "evening-golden",
      "camera": "COOLPIX S9900",
      "focalLengthMm": 5.2,
      "fNumber": 3.7,
      "shutter": "1/500",
      "iso": 125
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Henry_Plant_Museum_Fletcher_Lounge_ballroom_rotunda.jpg/1280px-Henry_Plant_Museum_Fletcher_Lounge_ballroom_rotunda.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Henry_Plant_Museum_Fletcher_Lounge_ballroom_rotunda.jpg/500px-Henry_Plant_Museum_Fletcher_Lounge_ballroom_rotunda.jpg",
      "caption": "Ornate Gilded-Age rotunda dome ceiling",
      "credit": "PeaceLoveHarmony",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHenry_Plant_Museum_Fletcher_Lounge_ballroom_rotunda.jpg",
      "light": "daytime",
      "camera": "SM-G930VL",
      "focalLengthMm": 4.2,
      "fNumber": 1.7,
      "shutter": "1/60",
      "iso": 160
    }
  ],
  "sacred-heart-catholic-church": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/9/92/Tampa_Sacred_Heart_Church04.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Tampa_Sacred_Heart_Church04.jpg/500px-Tampa_Sacred_Heart_Church04.jpg",
      "caption": "Marble facade and rose window against clouds",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Sacred_Heart_Church04.jpg",
      "light": "daytime"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Interior_Sacred_Heart_Catholic_Church%2C_Tampa%2C_Florida.jpg/1280px-Interior_Sacred_Heart_Catholic_Church%2C_Tampa%2C_Florida.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Interior_Sacred_Heart_Catholic_Church%2C_Tampa%2C_Florida.jpg/500px-Interior_Sacred_Heart_Catholic_Church%2C_Tampa%2C_Florida.jpg",
      "caption": "Ornate nave and marble columns to altar",
      "credit": "Boston Public Library",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AInterior_Sacred_Heart_Catholic_Church%2C_Tampa%2C_Florida.jpg",
      "camera": "Exp10000XL10000"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Tampa_Sacred_Heart_Church06.jpg/1280px-Tampa_Sacred_Heart_Church06.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Tampa_Sacred_Heart_Church06.jpg/500px-Tampa_Sacred_Heart_Church06.jpg",
      "caption": "Front-quarter view with dome on Florida Ave",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Sacred_Heart_Church06.jpg",
      "light": "daytime",
      "camera": "KODAK EASYSHARE C195 Digital Camera",
      "focalLengthMm": 5.9,
      "fNumber": 8,
      "shutter": "1/160",
      "iso": 64
    }
  ],
  "tampa-theatre": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Tampa_Theatre_2013.jpg/1280px-Tampa_Theatre_2013.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Tampa_Theatre_2013.jpg/500px-Tampa_Theatre_2013.jpg",
      "caption": "Neon marquee and blade sign glowing at night",
      "credit": "MarieG33",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampa_Theatre_2013.jpg",
      "light": "night-astro",
      "camera": "NIKON D60",
      "focalLengthMm": 18,
      "fNumber": 3.5,
      "shutter": "1/15",
      "iso": 400
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/TampaTheatre_front05.jpg/1280px-TampaTheatre_front05.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/TampaTheatre_front05.jpg/500px-TampaTheatre_front05.jpg",
      "caption": "Iconic vertical TAMPA blade sign from below",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampaTheatre_front05.jpg",
      "light": "daytime",
      "camera": "KODAK C875 ZOOM DIGITAL CAMERA",
      "focalLengthMm": 7.8,
      "fNumber": 2.8,
      "shutter": "1/100",
      "iso": 64
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/a/a4/TampaTheatre01.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/TampaTheatre01.jpg/500px-TampaTheatre01.jpg",
      "caption": "Marquee and office building with palms",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ATampaTheatre01.jpg",
      "light": "daytime"
    }
  ],
  "ybor-city": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/White_tower_in_Ybor_City%2C_Tampa_Florida.jpg/1280px-White_tower_in_Ybor_City%2C_Tampa_Florida.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/White_tower_in_Ybor_City%2C_Tampa_Florida.jpg/500px-White_tower_in_Ybor_City%2C_Tampa_Florida.jpg",
      "caption": "Historic corner building with green-tiled tower",
      "credit": "psyberartist",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWhite_tower_in_Ybor_City%2C_Tampa_Florida.jpg",
      "light": "daytime",
      "camera": "Canon EOS 6D",
      "focalLengthMm": 62,
      "fNumber": 22,
      "shutter": "1/160",
      "iso": 400
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Centro_Ybor%2C_Ybor_City%2C_Tampa%2C_Florida.jpg/1280px-Centro_Ybor%2C_Ybor_City%2C_Tampa%2C_Florida.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Centro_Ybor%2C_Ybor_City%2C_Tampa%2C_Florida.jpg/500px-Centro_Ybor%2C_Ybor_City%2C_Tampa%2C_Florida.jpg",
      "caption": "Centro Ybor facade with vintage streetcar",
      "credit": "Peter K Burian",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACentro_Ybor%2C_Ybor_City%2C_Tampa%2C_Florida.jpg",
      "light": "daytime",
      "camera": "NIKON D800",
      "focalLengthMm": 38,
      "fNumber": 4,
      "shutter": "1/1250",
      "iso": 500
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ybor_City_Museum_State_Park%2C_Tampa%2C_Florida.jpg/1280px-Ybor_City_Museum_State_Park%2C_Tampa%2C_Florida.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ybor_City_Museum_State_Park%2C_Tampa%2C_Florida.jpg/500px-Ybor_City_Museum_State_Park%2C_Tampa%2C_Florida.jpg",
      "caption": "Yellow-brick Ybor City Museum with flags",
      "credit": "Peter K Burian",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AYbor_City_Museum_State_Park%2C_Tampa%2C_Florida.jpg",
      "light": "daytime",
      "camera": "NIKON D800",
      "focalLengthMm": 40,
      "fNumber": 6.3,
      "shutter": "1/400",
      "iso": 400
    }
  ],
  "lettuce-lake-park": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Great_Blue_Heron_%2849111167428%29.jpg/1280px-Great_Blue_Heron_%2849111167428%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Great_Blue_Heron_%2849111167428%29.jpg/500px-Great_Blue_Heron_%2849111167428%29.jpg",
      "caption": "Great blue heron perched over still water",
      "credit": "Trish Hartmann from Tampa, Florida, USA",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AGreat_Blue_Heron_(49111167428).jpg",
      "light": "morning-golden",
      "camera": "NIKON D850",
      "focalLengthMm": 300,
      "fNumber": 5.6,
      "shutter": "1/750",
      "iso": 160
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Kayaking_on_the_Hillsborough_River.jpg/1280px-Kayaking_on_the_Hillsborough_River.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Kayaking_on_the_Hillsborough_River.jpg/500px-Kayaking_on_the_Hillsborough_River.jpg",
      "caption": "Cypress and palm mirrored in calm river",
      "credit": "Mwanner",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AKayaking_on_the_Hillsborough_River.jpg",
      "light": "daytime"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Barred_Owl_at_Lettuce_Lake_%2812735495095%29.jpg/1280px-Barred_Owl_at_Lettuce_Lake_%2812735495095%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Barred_Owl_at_Lettuce_Lake_%2812735495095%29.jpg/500px-Barred_Owl_at_Lettuce_Lake_%2812735495095%29.jpg",
      "caption": "Barred owl on a mossy branch",
      "credit": "Trish Hartmann from Tampa, Florida, USA",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABarred_Owl_at_Lettuce_Lake_(12735495095).jpg",
      "light": "open-shade",
      "camera": "NIKON D5100",
      "focalLengthMm": 200,
      "fNumber": 5.6,
      "shutter": "1/320",
      "iso": 400
    }
  ],
  "usf-botanical-gardens": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Dyckia_Red2_USF_Asit.jpg/1280px-Dyckia_Red2_USF_Asit.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Dyckia_Red2_USF_Asit.jpg/500px-Dyckia_Red2_USF_Asit.jpg",
      "caption": "Vivid red bromeliad rosette, exotic collection",
      "credit": "Asit K. Ghosh Thaumaturgist",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ADyckia_Red2_USF_Asit.jpg",
      "light": "daytime",
      "camera": "DSC-H9",
      "focalLengthMm": 6.8,
      "fNumber": 4,
      "shutter": "1/200",
      "iso": 100
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/BalsamPear02_USF_Asit.JPG/1280px-BalsamPear02_USF_Asit.JPG",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/BalsamPear02_USF_Asit.JPG/500px-BalsamPear02_USF_Asit.JPG",
      "caption": "Backlit orange fruit glowing in foliage",
      "credit": "asitkghosh@yahoo.com Thaumaturgist",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABalsamPear02_USF_Asit.JPG",
      "light": "daytime",
      "camera": "DSC-H9",
      "focalLengthMm": 19,
      "fNumber": 4.5,
      "shutter": "1/500",
      "iso": 100
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/BalsamPear04_USF_Asit.JPG/1280px-BalsamPear04_USF_Asit.JPG",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/BalsamPear04_USF_Asit.JPG/500px-BalsamPear04_USF_Asit.JPG",
      "caption": "Bright orange bloom among lush greenery",
      "credit": "asitkghosh@yahoo.com Thaumaturgist",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABalsamPear04_USF_Asit.JPG",
      "light": "daytime",
      "camera": "DSC-H9",
      "focalLengthMm": 14,
      "fNumber": 4.5,
      "shutter": "1/400",
      "iso": 100
    }
  ],
  "sunken-gardens": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/0/09/Coy_pond_at_the_entrance_to_the_Sunken_Gardens-_St._Petersburg%2C_Florida_%288527270077%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Coy_pond_at_the_entrance_to_the_Sunken_Gardens-_St._Petersburg%2C_Florida_%288527270077%29.jpg/500px-Coy_pond_at_the_entrance_to_the_Sunken_Gardens-_St._Petersburg%2C_Florida_%288527270077%29.jpg",
      "caption": "Grotto waterfall over koi-and-lily pond",
      "credit": "Florida Memory",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACoy_pond_at_the_entrance_to_the_Sunken_Gardens-_St._Petersburg%2C_Florida_(8527270077).jpg",
      "light": "daytime"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/3/35/Scarlet_Ibis_at_Sunken_Gardens-_St._Petersburg%2C_Florida_%288528405744%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Scarlet_Ibis_at_Sunken_Gardens-_St._Petersburg%2C_Florida_%288528405744%29.jpg/500px-Scarlet_Ibis_at_Sunken_Gardens-_St._Petersburg%2C_Florida_%288528405744%29.jpg",
      "caption": "Scarlet ibis portrait in soft shade",
      "credit": "Florida Memory",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AScarlet_Ibis_at_Sunken_Gardens-_St._Petersburg%2C_Florida_(8528405744).jpg",
      "light": "open-shade"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/St._Petersburg_FL_Sunken_Gardens_gate01.jpg/1280px-St._Petersburg_FL_Sunken_Gardens_gate01.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/St._Petersburg_FL_Sunken_Gardens_gate01.jpg/500px-St._Petersburg_FL_Sunken_Gardens_gate01.jpg",
      "caption": "Gate framed by bougainvillea and palms",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Petersburg_FL_Sunken_Gardens_gate01.jpg",
      "light": "open-shade",
      "camera": "KODAK EASYSHARE C195 Digital Camera",
      "focalLengthMm": 5.9,
      "fNumber": 3.3,
      "shutter": "1/60",
      "iso": 64
    }
  ],
  "fort-de-soto-park": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Sunset_on_North_Beach_at_Fort_De_Soto_Park.jpg/1280px-Sunset_on_North_Beach_at_Fort_De_Soto_Park.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Sunset_on_North_Beach_at_Fort_De_Soto_Park.jpg/500px-Sunset_on_North_Beach_at_Fort_De_Soto_Park.jpg",
      "caption": "Gulf sunset over calm North Beach surf",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASunset_on_North_Beach_at_Fort_De_Soto_Park.jpg",
      "light": "sunset",
      "camera": "CYBERSHOT",
      "focalLengthMm": 7,
      "fNumber": 4.8,
      "shutter": "1/470",
      "iso": 100
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Fort_de_Soto_Park_%40_St.Petersburg_%28Florida_-_Gulfcoast%29_%2815684290600%29.jpg/1280px-Fort_de_Soto_Park_%40_St.Petersburg_%28Florida_-_Gulfcoast%29_%2815684290600%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Fort_de_Soto_Park_%40_St.Petersburg_%28Florida_-_Gulfcoast%29_%2815684290600%29.jpg/500px-Fort_de_Soto_Park_%40_St.Petersburg_%28Florida_-_Gulfcoast%29_%2815684290600%29.jpg",
      "caption": "White-sand spit and lagoon with passing yacht",
      "credit": "Reinhard Link from Germany",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AFort_de_Soto_Park_%40_St.Petersburg_(Florida_-_Gulfcoast)_(15684290600).jpg",
      "light": "daytime",
      "camera": "EX-H15",
      "focalLengthMm": 22,
      "fNumber": 5.2,
      "shutter": "1/800",
      "iso": 64
    }
  ],
  "honeymoon-island-sp": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Honeymoon_Island_State_Park_%28Image_1%29.jpg/1280px-Honeymoon_Island_State_Park_%28Image_1%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Honeymoon_Island_State_Park_%28Image_1%29.jpg/500px-Honeymoon_Island_State_Park_%28Image_1%29.jpg",
      "caption": "Turquoise Gulf surf on shell beach",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoneymoon_Island_State_Park_(Image_1).jpg",
      "light": "daytime",
      "camera": "CYBERSHOT",
      "focalLengthMm": 7,
      "fNumber": 8,
      "shutter": "1/985",
      "iso": 100
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Honeymoon_Island_State_Park_%28Image_3%29.jpg/1280px-Honeymoon_Island_State_Park_%28Image_3%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Honeymoon_Island_State_Park_%28Image_3%29.jpg/500px-Honeymoon_Island_State_Park_%28Image_3%29.jpg",
      "caption": "Wooden swing facing the Gulf",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoneymoon_Island_State_Park_(Image_3).jpg",
      "light": "daytime",
      "camera": "CYBERSHOT",
      "focalLengthMm": 7,
      "fNumber": 8,
      "shutter": "1/985",
      "iso": 100
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Honeymoon_Island_State_Park_%28Image_2%29.jpg/1280px-Honeymoon_Island_State_Park_%28Image_2%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Honeymoon_Island_State_Park_%28Image_2%29.jpg/500px-Honeymoon_Island_State_Park_%28Image_2%29.jpg",
      "caption": "Leaning tree over shell shoreline",
      "credit": "Christopher Hollis",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoneymoon_Island_State_Park_(Image_2).jpg",
      "light": "daytime",
      "camera": "CYBERSHOT",
      "focalLengthMm": 7,
      "fNumber": 8,
      "shutter": "1/985",
      "iso": 100
    }
  ],
  "sunshine-skyway-fishing-piers": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Sunshine_Skyway_Bridge.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Sunshine_Skyway_Bridge.jpg",
      "caption": "Lit Skyway span over the bay at dusk",
      "credit": "The original uploader was Caltrop at English Wikipedia .",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASunshine_Skyway_Bridge.jpg",
      "light": "blue-hour"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/2010-09-10_Sunshine_Skyway_Bridge.jpg/1280px-2010-09-10_Sunshine_Skyway_Bridge.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/2010-09-10_Sunshine_Skyway_Bridge.jpg/500px-2010-09-10_Sunshine_Skyway_Bridge.jpg",
      "caption": "Yellow cables fanning to the tower",
      "credit": "Joe King",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A2010-09-10_Sunshine_Skyway_Bridge.jpg",
      "light": "daytime",
      "camera": "u720SW,S720SW",
      "focalLengthMm": 6.7,
      "fNumber": 5,
      "shutter": "1/320",
      "iso": 64
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Sunshine_Skyway_Bridge_1SC_2563.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Sunshine_Skyway_Bridge_1SC_2563.jpg/500px-Sunshine_Skyway_Bridge_1SC_2563.jpg",
      "caption": "Bridge silhouette with cargo ship at golden hour",
      "credit": "Robert Neff",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASunshine_Skyway_Bridge_1SC_2563.jpg",
      "light": "evening-golden",
      "camera": "NIKON D7000",
      "focalLengthMm": 60,
      "fNumber": 16,
      "shutter": "1/160",
      "iso": 100
    }
  ],
  "st-pete-pier": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/2021_St._Pete_Pier_1.jpg/1280px-2021_St._Pete_Pier_1.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/2021_St._Pete_Pier_1.jpg/500px-2021_St._Pete_Pier_1.jpg",
      "caption": "Modern pier head with palms, blue sky",
      "credit": "Beyond My Ken",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3A2021_St._Pete_Pier_1.jpg",
      "light": "daytime",
      "camera": "iPhone 8",
      "focalLengthMm": 4,
      "fNumber": 1.8,
      "shutter": "1/2558"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/St._Pete_Pier_-_West.jpg/1280px-St._Pete_Pier_-_West.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/St._Pete_Pier_-_West.jpg/500px-St._Pete_Pier_-_West.jpg",
      "caption": "Bending Arc net sculpture overhead",
      "credit": "Jackdude101",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Pier_-_West.jpg",
      "light": "daytime",
      "camera": "DSC-W830",
      "focalLengthMm": 4.5,
      "fNumber": 8,
      "shutter": "1/200",
      "iso": 80
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/St._Pete_Pier_head_structure.jpg/1280px-St._Pete_Pier_head_structure.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/St._Pete_Pier_head_structure.jpg/500px-St._Pete_Pier_head_structure.jpg",
      "caption": "Pier head structure over the bay",
      "credit": "Adog",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Pier_head_structure.jpg",
      "light": "daytime",
      "camera": "iPhone 11",
      "focalLengthMm": 4.3,
      "fNumber": 1.8,
      "shutter": "1/2315",
      "iso": 32
    }
  ],
  "vinoy-park": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/St._Pete_Vinoy_pano01.jpg/1280px-St._Pete_Vinoy_pano01.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/St._Pete_Vinoy_pano01.jpg/500px-St._Pete_Vinoy_pano01.jpg",
      "caption": "Pink Vinoy hotel framed by palms",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Vinoy_pano01.jpg",
      "light": "daytime"
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/The_Vinoy_Hotel_04.jpg/1280px-The_Vinoy_Hotel_04.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/The_Vinoy_Hotel_04.jpg/500px-The_Vinoy_Hotel_04.jpg",
      "caption": "Ornate VINOY window with palm",
      "credit": "MiaCass16",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AThe_Vinoy_Hotel_04.jpg",
      "light": "daytime",
      "camera": "DSC-H300",
      "focalLengthMm": 4.5,
      "fNumber": 3,
      "shutter": "1/1000",
      "iso": 80
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/St._Pete_Vinoy_detail02.jpg/1280px-St._Pete_Vinoy_detail02.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/St._Pete_Vinoy_detail02.jpg/500px-St._Pete_Vinoy_detail02.jpg",
      "caption": "Pink facade detail against blue sky",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Vinoy_detail02.jpg",
      "light": "daytime",
      "camera": "KODAK C875 ZOOM DIGITAL CAMERA",
      "focalLengthMm": 24,
      "fNumber": 5,
      "shutter": "1/500",
      "iso": 64
    }
  ],
  "dali-museum": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Salvador_Dali_Museum_-_panoramio_%2817%29.jpg/1280px-Salvador_Dali_Museum_-_panoramio_%2817%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Salvador_Dali_Museum_-_panoramio_%2817%29.jpg/500px-Salvador_Dali_Museum_-_panoramio_%2817%29.jpg",
      "caption": "Enigma glass bubble framed by cypress, dramatic sky",
      "credit": "Art Anderson",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASalvador_Dali_Museum_-_panoramio_(17).jpg",
      "light": "evening-golden",
      "camera": "Canon PowerShot S120",
      "focalLengthMm": 6,
      "fNumber": 3.5,
      "shutter": "1/2000",
      "iso": 160
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Salvador_Dal%C3%AD_Museum.JPG/1280px-Salvador_Dal%C3%AD_Museum.JPG",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Salvador_Dal%C3%AD_Museum.JPG/500px-Salvador_Dal%C3%AD_Museum.JPG",
      "caption": "Full Enigma bubble and concrete museum, palms",
      "credit": "Taty2007",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASalvador_Dal%C3%AD_Museum.JPG",
      "light": "daytime",
      "camera": "Canon EOS 50D",
      "focalLengthMm": 28,
      "fNumber": 7.1,
      "shutter": "1/160",
      "iso": 100
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Atrium_of_Salvador_Dal%C3%AD_Museum_in_Florida.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Atrium_of_Salvador_Dal%C3%AD_Museum_in_Florida.jpg/500px-Atrium_of_Salvador_Dal%C3%AD_Museum_in_Florida.jpg",
      "caption": "Helical staircase under the geodesic glass dome",
      "credit": "LovelyLillith",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AAtrium_of_Salvador_Dal%C3%AD_Museum_in_Florida.jpg",
      "light": "daytime",
      "camera": "Lumia 925",
      "fNumber": 2,
      "shutter": "1/1299",
      "iso": 100
    }
  ],
  "weedon-island-preserve": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Weedon_Island_preserve_-_panoramio.jpg/1280px-Weedon_Island_preserve_-_panoramio.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Weedon_Island_preserve_-_panoramio.jpg/500px-Weedon_Island_preserve_-_panoramio.jpg",
      "caption": "Mangrove boardwalk leading into the preserve",
      "credit": "jesseasmith",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWeedon_Island_preserve_-_panoramio.jpg",
      "light": "daytime",
      "camera": "NIKON D5000",
      "focalLengthMm": 10,
      "fNumber": 10,
      "shutter": "1/250",
      "iso": 200
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Weedon_Island_preserve_-_panoramio_%282%29.jpg/1280px-Weedon_Island_preserve_-_panoramio_%282%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Weedon_Island_preserve_-_panoramio_%282%29.jpg/500px-Weedon_Island_preserve_-_panoramio_%282%29.jpg",
      "caption": "Boardwalk vanishing under towering cumulus clouds",
      "credit": "jesseasmith",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWeedon_Island_preserve_-_panoramio_(2).jpg",
      "light": "daytime",
      "camera": "NIKON D5000",
      "focalLengthMm": 10,
      "fNumber": 11,
      "shutter": "1/640",
      "iso": 200
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Weeden_Island01.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Weeden_Island01.jpg/500px-Weeden_Island01.jpg",
      "caption": "Mangrove wetlands and bay from tower",
      "credit": "Ebyabe",
      "license": "CC BY 2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AWeeden_Island01.jpg",
      "light": "daytime"
    }
  ],
  "cathedral-st-peter-episcopal": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/1/1f/St_Petersburg%2C_FL_-_Downtown_St_Petersburg_Historic_District_-_Cathedral_Church_of_St_Peter_%28Episcopal%29_%283%29.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/St_Petersburg%2C_FL_-_Downtown_St_Petersburg_Historic_District_-_Cathedral_Church_of_St_Peter_%28Episcopal%29_%283%29.jpg/500px-St_Petersburg%2C_FL_-_Downtown_St_Petersburg_Historic_District_-_Cathedral_Church_of_St_Peter_%28Episcopal%29_%283%29.jpg",
      "caption": "Brick gable, stained glass and spire",
      "credit": "Jrozwado",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt_Petersburg%2C_FL_-_Downtown_St_Petersburg_Historic_District_-_Cathedral_Church_of_St_Peter_(Episcopal)_(3).jpg",
      "light": "evening-golden",
      "camera": "NIKON D7100",
      "focalLengthMm": 24,
      "fNumber": 16,
      "shutter": "1/1000",
      "iso": 1250
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/St._Pete_Episc_Cathedral03.jpg/1280px-St._Pete_Episc_Cathedral03.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/St._Pete_Episc_Cathedral03.jpg/500px-St._Pete_Episc_Cathedral03.jpg",
      "caption": "Blonde-brick spire against blue sky",
      "credit": "Ebyabe",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ASt._Pete_Episc_Cathedral03.jpg",
      "light": "daytime",
      "camera": "KODAK C875 ZOOM DIGITAL CAMERA",
      "focalLengthMm": 7.8,
      "fNumber": 4,
      "shutter": "1/800",
      "iso": 64
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Cathedral_Church_of_St._Peter_at_140_4th_St._N._in_St._Petersburg%2C_Florida.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Cathedral_Church_of_St._Peter_at_140_4th_St._N._in_St._Petersburg%2C_Florida.jpg/500px-Cathedral_Church_of_St._Peter_at_140_4th_St._N._in_St._Petersburg%2C_Florida.jpg",
      "caption": "Full three-quarter view of cathedral",
      "credit": "Joseph Janney Steinmetz",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_Church_of_St._Peter_at_140_4th_St._N._in_St._Petersburg%2C_Florida.jpg",
      "light": "daytime"
    }
  ],
  "cathedral-st-jude-apostle": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_sanctuary_2.jpg/1280px-Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_sanctuary_2.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_sanctuary_2.jpg/500px-Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_sanctuary_2.jpg",
      "caption": "Altar and crucifix with modern stained glass",
      "credit": "Nheyob",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_of_Saint_Jude_the_Apostle_(St._Petersburg%2C_Florida)_-_sanctuary_2.jpg",
      "light": "daytime",
      "camera": "Canon PowerShot G9 X",
      "focalLengthMm": 11,
      "fNumber": 2.8,
      "shutter": "1/30",
      "iso": 125
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_nave.jpg/1280px-Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_nave.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_nave.jpg/500px-Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_nave.jpg",
      "caption": "Nave pews toward the altar",
      "credit": "Nheyob",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_of_Saint_Jude_the_Apostle_(St._Petersburg%2C_Florida)_-_nave.jpg",
      "light": "daytime",
      "camera": "Canon PowerShot G9 X",
      "focalLengthMm": 10,
      "fNumber": 2.2,
      "shutter": "1/60",
      "iso": 125
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_exterior.jpg/1280px-Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_exterior.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_exterior.jpg/500px-Cathedral_of_Saint_Jude_the_Apostle_%28St._Petersburg%2C_Florida%29_-_exterior.jpg",
      "caption": "Orange spire and cathedral name sign",
      "credit": "Nheyob",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ACathedral_of_Saint_Jude_the_Apostle_(St._Petersburg%2C_Florida)_-_exterior.jpg",
      "light": "daytime",
      "camera": "Canon PowerShot G9 X",
      "focalLengthMm": 10,
      "fNumber": 4,
      "shutter": "1/100",
      "iso": 160
    }
  ],
  "stpete-shine-murals": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Before_I_Die_Mural.jpg/1280px-Before_I_Die_Mural.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Before_I_Die_Mural.jpg/500px-Before_I_Die_Mural.jpg",
      "caption": "\"Before I die\" wall with bikes, people",
      "credit": "Xrzt",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3ABefore_I_Die_Mural.jpg",
      "light": "daytime",
      "camera": "NIKON D7000",
      "focalLengthMm": 50,
      "fNumber": 6.3,
      "shutter": "1/2000",
      "iso": 200
    }
  ],
  "fred-howard-park": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Howard_Park_Tarpon.jpg/1280px-Howard_Park_Tarpon.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Howard_Park_Tarpon.jpg/500px-Howard_Park_Tarpon.jpg",
      "caption": "Gulf sunset behind beach palm silhouettes",
      "credit": "VitaleBaby at English Wikipedia",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3AHoward_Park_Tarpon.jpg",
      "light": "sunset",
      "camera": "Canon PowerShot ELPH 350 HS",
      "focalLengthMm": 20,
      "fNumber": 5,
      "shutter": "1/500",
      "iso": 250
    },
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Porsche_and_parasail.jpg/1280px-Porsche_and_parasail.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Porsche_and_parasail.jpg/500px-Porsche_and_parasail.jpg",
      "caption": "Kite-surfer rig over windy causeway",
      "credit": "Xrzt",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File%3APorsche_and_parasail.jpg",
      "light": "daytime",
      "camera": "NIKON D7000",
      "focalLengthMm": 180,
      "fNumber": 9,
      "shutter": "1/1250",
      "iso": 200
    }
  ],
  "azure-tampa-edition": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/EditionTampa.jpg/1280px-EditionTampa.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/EditionTampa.jpg/500px-EditionTampa.jpg",
      "caption": "The Tampa EDITION — home of the Azure rooftop",
      "credit": "Chiefmiz",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:EditionTampa.jpg",
      "light": "daytime"
    }
  ],
  "beacon-jw-marriott": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Downtown_Tampa%2C_Florida.jpg/1280px-Downtown_Tampa%2C_Florida.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Downtown_Tampa%2C_Florida.jpg/500px-Downtown_Tampa%2C_Florida.jpg",
      "caption": "Downtown Tampa skyline — the kind of view from the rooftop",
      "credit": "Clément Bardot",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Downtown_Tampa,_Florida.jpg",
      "light": "daytime",
      "camera": "NIKON D5100",
      "focalLengthMm": 22,
      "fNumber": 7.1,
      "shutter": "1/1600",
      "iso": 400
    }
  ],
  "mbird-armature-works": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Tampa_Skyline_-_Eric_Statzer.jpg/1280px-Tampa_Skyline_-_Eric_Statzer.jpg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Tampa_Skyline_-_Eric_Statzer.jpg/500px-Tampa_Skyline_-_Eric_Statzer.jpg",
      "caption": "Downtown skyline across the water from the Heights",
      "credit": "Eric Statzer",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tampa_Skyline_-_Eric_Statzer.jpg",
      "light": "daytime",
      "camera": "iPhone X",
      "focalLengthMm": 4,
      "fNumber": 1.8,
      "shutter": "1/1919"
    }
  ],
  "edge-epicurean": [
    {
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Downtown_Tampa_%2858977580%29.jpeg/1280px-Downtown_Tampa_%2858977580%29.jpeg",
      "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Downtown_Tampa_%2858977580%29.jpeg/500px-Downtown_Tampa_%2858977580%29.jpeg",
      "caption": "The distant downtown skyline at golden hour",
      "credit": "Steven Buehler",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Downtown_Tampa_(58977580).jpeg",
      "light": "evening-golden",
      "camera": "COOLPIX L820",
      "focalLengthMm": 76,
      "fNumber": 5.7,
      "shutter": "1/125",
      "iso": 125
    }
  ],
  "tampa-murals": [
    {
      "src": "https://live.staticflickr.com/3875/14492170902_aeffc419dd_b.jpg",
      "thumb": "https://live.staticflickr.com/3875/14492170902_aeffc419dd_z.jpg",
      "caption": "The 'Tampa Postcard' mural (by Carl Cowden III) at golden hour",
      "credit": "Photomatt28 (Flickr)",
      "license": "CC BY-NC-ND 2.0",
      "sourceUrl": "https://www.flickr.com/photos/46837385@N03/14492170902",
      "light": "evening-golden"
    }
  ]
}
